### PR TITLE
Test: make tests execute on PHP 8/PHPUnit 8

### PR DESCRIPTION
**Pull request by micgro42**
This is needed for the tests to be run at all on DokuWiki master and with PHPunit 8.

Each commit fixes another chunk of tests.

### CODE REVIEW

**Comment by splitbrain** [comment]
Hmm. Shouldn't this have been run on github? I only see travis? Also can you remove the travis config?

**Comment by micgro42** [comment]
I'll remove the travis config.

You don't see GitHub, because this PR comes from a fork. Otherwise I could ninja some CI into your repo and print all your secret deploy keys into the logs :p

**Comment by annda** [comment]
@splitbrain Can you merge this now that the testing configuration has been replaced?

**Comment by micgro42** [comment]
> @micgro42 if I would let anyone ninja into my repos it would be you ;-)

Aww :heart:

**Pull request merged**
