### PR TITLE
Add from field to mail action

### PR DESCRIPTION
**Pull request by andreasbenzing**
The field allows users to set the From header in the mail action.

### CODE REVIEW

**Comment by Klap-in** [comment]
There is already Reply-To, why do you not use that?

**Comment by andreasbenzing** [comment]
We feed the mails directly into a ticket system which cannot handle the
Reply-To header.

**Comment by frafum** [comment]
Thanks andreasbenzing for creating this patch. 

I hope that it will be merged into the dokuwiki main branch. In fact, when using the mail action with a template, the from address has mail_pphp in its From field. This is not helpful for people that are not very literate in informatics. 

An explicit From address that they can use when something goes wrong would be more helpful to them.

**Comment by andreasbenzing** [comment]
Since it's been way over two years, I don't expect this will happen. I also completely forgot about this MR.

**Comment by frafum** [comment]
Hi Andreas, 

Thanks for your feedback. 

However, I don't understand why you closed this MR. It is IMHO still a valid request.

**Comment by andreasbenzing** [comment]
That was not intended. Unfortunately, I cannot reopen it because the source is gone. Feel free to cherry pick the commit and reopen a new request.

**Pull request closed without merging**
